/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const CampaignLazyRouteImport = createFileRoute('/campaign')()
const AccountLazyRouteImport = createFileRoute('/account')()
const CampaignOverviewIdLazyRouteImport = createFileRoute(
  '/campaignOverview/$id',
)()

const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const CampaignLazyRoute = CampaignLazyRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/campaign.lazy').then((d) => d.Route))
const AccountLazyRoute = AccountLazyRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignOverviewIdLazyRoute = CampaignOverviewIdLazyRouteImport.update({
  id: '/campaignOverview/$id',
  path: '/campaignOverview/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/campaignOverview.$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountLazyRoute
  '/campaign': typeof CampaignLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/campaignOverview/$id': typeof CampaignOverviewIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountLazyRoute
  '/campaign': typeof CampaignLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/campaignOverview/$id': typeof CampaignOverviewIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountLazyRoute
  '/campaign': typeof CampaignLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/campaignOverview/$id': typeof CampaignOverviewIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/campaign'
    | '/dashboard'
    | '/campaignOverview/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/campaign' | '/dashboard' | '/campaignOverview/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/campaign'
    | '/dashboard'
    | '/campaignOverview/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountLazyRoute: typeof AccountLazyRoute
  CampaignLazyRoute: typeof CampaignLazyRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  CampaignOverviewIdLazyRoute: typeof CampaignOverviewIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaignOverview/$id': {
      id: '/campaignOverview/$id'
      path: '/campaignOverview/$id'
      fullPath: '/campaignOverview/$id'
      preLoaderRoute: typeof CampaignOverviewIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountLazyRoute: AccountLazyRoute,
  CampaignLazyRoute: CampaignLazyRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  CampaignOverviewIdLazyRoute: CampaignOverviewIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
